### PR TITLE
Draft: add async-enabled view for flask

### PR DESCRIPTION
**Pull request by scottweitzner**

### CODE REVIEW

**Comment by patrick91** [comment]
Hi @scottweitzner! this looks great, would be ok to add one test?

**Comment by patrick91** [comment]
oh, also I just noticed this PR is targeting your own repo and not the strawberry one 😊

**Comment by scottweitzner** [comment]
Hey Patrick, thanks for taking a look! I didn't want to bog y'all down in the official repo, but since you said this looks good I'll create an MR pointed at the official repo. I'll add a test before doing so

**Comment by scottweitzner** [comment]
closing in favor of https://github.com/strawberry-graphql/strawberry/pull/1907

**Pull request closed without merging**
